server:
  port: 9090


spring:
  devtools:
    restart:
      log-condition-evaluation-delta: true # 是否打印更新日志  default true
      exclude: static/**,templates/**

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    suffix: .html
    prefix: classpath:/templates/
    enabled: true
  application:
    name: demo
  activemq:
    pool:
      enabled: true
      max-connections: 50
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:61616
    in-memory: true
  redis:
    host: 127.0.0.1
    port: 6379


gate:
  jwt:
    secret: sGesf$^#3din
    expiration: 7200


