server:
  port: 9090


spring:
  devtools:
    restart:
      log-condition-evaluation-delta: true # 是否打印更新日志  default true
      exclude: static/**,templates/**

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    suffix: .html
    prefix: classpath:/templates/
    enabled: true
  application:
    name: demo

gate:
  jwt:
    secret: sGesf$^#3din
    expiration: 7200
